### ISSUE TITLE
Polygon columns

### ISSUE THREAD

**Issue by ghost** [LegendOfMCPE/WorldEditArt#11] opened 2016-03-31 22:08 UTC
The idea is that is the world editor makes customized shapes for you. You can make as many positions as you want and the world editor will fill in blocks from those selected positions. Set 3 positions and you can make a triangle or do some weird things to make a star, lol. Hope you like my idea! ^^

**Comment by PEMapModder** [comment] 2016-04-01 00:00
How is this different from the current system? Can you give an example what s user sees?

**Comment by Tolo0** [comment] 2016-04-01 00:02
I think he means like. set 3 positions so u could make like a triangle or set 12 positions to make like a cross shape lol

**Comment by ghost** [comment] 2016-04-01 00:06
Yes, exactly.

**Comment by ghost** [comment] 2016-04-01 00:09
By the way please make sure leet servers don't use this plugin. I really hate leet. They literally steal plugins that are copyrighted and do illieagal things. Make a thing on your plugin saying leet can't use this plugin.

**Comment by Tolo0** [comment] 2016-04-01 00:23
I think leet are already using it lol

**Comment by Lucario2** [comment] 2016-04-01 00:24
FUCK LEET. FUCK YOU LEET

**Comment by Tolo0** [comment] 2016-04-01 00:26
u know the majority of the servers around. are leet.

**Comment by Lucario2** [comment] 2016-04-01 00:26
Yes, that's why I'm so fucking pissed. I'm sorry.

**Comment by PEMapModder** [comment] 2016-04-01 09:02
WorldEditArt is an open-source project. It shall be available to all users for legal purposes. I do not see how this plugin can be used to carry out illegal activities. If everyone acts like this, disallowing people that he personally hates to use their own things, there will never be evolution in the world.

**Comment by PEMapModder** [comment] 2016-04-01 09:07
And please do not post comments that are irrelevant to the issue. If it is another issue related to this repo, please create an issue.

**Comment by PEMapModder** [comment] 2016-04-03 15:59
Interesting. Confirmed.

**Comment by ghost** [comment] 2016-04-07 00:10
PeMapModder? Do you like this idea? I just wanted to add some ideas while the plugin was being developed.

Please tell me if you like the idea
In the future... If you let... I would like to suggest more ideas ^^

**Comment by PEMapModder** [comment] 2016-04-07 08:11
I'll not be adding it until the basic structure is stable.

**Comment by bbka123** [comment] 2016-07-25 13:59
```yaml
beta safety:

# this is a config file generated/updated by the beta release of (do not modify this line)

  version: 1.0.0_beta_dev_#044

# as a beta release, some features are not tested.

# For the sake of your server's safety, these features are disabled by default (marked as "false" below).

# If you want to enable these features, change them to "true".

# However, you are warned that these features may be dangerous. The effects might include simply not working,

# not doing exactly what you intended to, dealing damage to your world that can only be reversed by hand or

# by backups, or even crash your server. Please do NOT report bugs of these untested features to the forums

# release page reviews, forum release thread or the GitHub bug tracker.

# You can also disable features by setting those default "true" to "false".

  enabled features:
    selecting anchors: true # enable //anchors
    clipboard:
      copying: true # enable //copy
      cutting: false # enable //cut
      pasting: false # enable //paste
    selections:
      selecting selections:
        cuboid selection:
          by shoot: true # enable //shoot
          by grow: true # enable //grow
          # cuboid selection by two points is listed under the "miscellaneous" section below. A cuboid selection is automatically made when both //pos1 and //pos2 are selected.
        cylinder selection: true # enable //cylinder
        sphere selection: true # enable //sphere
        deselection: false # enable //desel
      testing selections: true # enable //test
      editing selections:
        setting blocks by command: ## //set
          any block types: true # if this is set to false, the command //set will not be registered and the following lines in this section are assumed "false".
          two block types without percentage: true # like //set stone,grass to set to stone and grass, each block with 50% chance
          two block types with percentage: true # like //set 10%stone,90%grass to set with their respective percentage chances
          multiple block types without percentage: false # like two block types except having at least three
          multiple block types with percentage: false # like two block types except having at least three
        replacing blocks by command: ## //replace
          # "target block type(s)" same as above for the block type to replace with (final block)
          any block types: true # if this is set to false, the command //replace will not be registered and the following lines in this section are assumed "false".
          two target block types without percentage: true
          two target block types with percentage: true
          multiple target block types without percentage: false
          multiple target block types with percentage: false
    macros: false # enable //macro
    miscellaneous:
      selecting points by //pos1 (or //1) and //pos2 (or //2): true # enable //pos1 and //pos2
      custom tool selection:
        jump: false # enable //jump
        wand: false # enable //wand
      jump: true # enable the feature of teleporting player to the block his crosshair is pointing at when he long-clicks air with the item of "jump-id":"jump-damage" below.
      # Note: jump is a bit buggy but safe enough to use.
      wand: false # enable the feature of making cuboid selections by clicking blocks with wands (equivalent to //pos1 and //pos2)

#### Data providers

## Data providers provide the plugin storages to store data

data providers:
  # Player data provider provides the plugin per-player data, such as personal wands
  player:
    # Choose a data provider type. Options:
    # sqlite3 (create an SQLite3 file as database)
    # yaml (save one YAML file for each player)
    # json (save one JSON file for each player)
    # mysqli (save on a remote MySQL database)
    type: sqlite3
    # SQLite3 options. If you use it, configure this properly.
    sqlite3:
      # The path to save the database. It will be saved in /.../PocketMine-MP/plugins/WorldEditArt/<path>. Enter <path> below. (Sub-folders will NOT be created automatically; create the directories yourself; use .. to jump up to parent folder)
      path: "players.sq3"
    # YAML options. If you use it, configure this properly.
    yaml:
      # The path to save files. It will be saved in /.../PocketMine-MP/plugins/WorldEditArt/<path>. Enter <path> below. (Sub-folders will be created automatically; you just need to use / (or / or \ if on Windows); use .. to jump up to parent folder)
      path: "players/yaml/<name>.yml"
    # JSON options. If you use it, configure this properly.
    json:
      # The path to save files. It will be saved in /.../PocketMine-MP/plugins/WorldEditArt/<path>. Enter <path> below. (Sub-folders will be created automatically; you just need to use / (or / or \ if on Windows); use .. to jump up to parent folder)
      path: "players/json/<name>.json"
      # Format the files beautifully. This will write unnecessary (and ignored when reading) indents and returns that eases your reading if you open/modify these files.
      pretty print: true
    # MySQLi options. If you use it, configure this properly.
    mysqli:
      use common: true
      host: example.com
      username: "guest"
      password: "123456IsNotAGoodPassword"
      database: "WorldEditArt player database"
      port: 3306

  # Macro data provider provides the plugin a storage of macros
  macro:
    # Choose a data provider type. Options:
    # mcr (save one .mcr file for each macro)
    # mysqli (save on a remote MySQL database)
    type: mcr
    # MCR options. If you use it, configure this properly.
    mcr:
      # The path to save files. It will be saved in /.../PocketMine-MP/plugins/WorldEditArt/<path>. Enter <path> below. (Sub-folders will be created automatically); you just need to use / (or / or \ if on Windows); use .. to jump up to parent folder
      path: "macros/<name>.mcr"
      # Compression of MCR files. Options:
      # 31 (compress with the GZIP format)
      # 0 (do not compress)
      # Warning: not using the formats above will cause unexpected errors.
      compression: 0 # TODO change this to 31 after debugging # This is an internal remark. If I forgot to remove this, please tell me.
    # MySQLi options. If you use it, configure this properly.
    mysqli:
      use common: true
      host: example.com
      username: "guest"
      password: "123456IsNotAGoodPassword"
      database: "WorldEditArt macro database"
      port: 3306

  # Clipboard data provider provides the plugin a clipboard to store clips
  clipboard:
    # Choose a data provider type. Options:
    # clp (save one .clp file for each clip)
    # mysqli (save on a remote MySQL database)
    type: clp
    # CLP options. If you use it, configure this properly.
    clp:
      # The path to save files. It will be saved in /.../PocketMine-MP/plugins/WorldEditArt/<path>. Enter <path> below. (Sub-folders will be created automatically; you just need to use / (or / or \ if on Windows); use .. to jump up to parent folder)
      path: "clipboard/<name>.clp"
    # MySQLi options. If you use it, configure this properly.
    mysqli:
      use common: true
      host: example.com
      username: "guest"
      password: "123456IsNotAGoodPassword"
      database: "WorldEditArt macro database"
      port: 3306

  # If you want all mysqli data providers to use the same mysqli database, configure this and set "use common" to true in each of them
  common mysqli database:
    host: example.com
    username: "guest"
    password: "123456IsNotAGoodPassword"
    database: "WorldEditArt_common_database"
    port: 3306
  # To increase efficiency, loaded data is saved in memory as "caches". How many seconds should these data be held in memory before collected (i.e. deleted) by the plugin?
  cache time: 120

#### Wands

# Wands set your anchor to the block you are pointing at

# The default wand item ID

wand-id: 292

# leave false for any values

wand-damage: false

#### Jump

# Jump is a feature where you click the screen with a specified item and you are teleported to the block your crosshair points at

# The default jump item ID

jump-id: 345

# leave false for any values

jump-damage: 0

#### Version compatibility

## Changing these value could lead to dangerous crashes.

# If PocketMine and MCPE are updated such that the world maximum height is no longer 127, change this. This value is NOT to increase the world height. It is only an in-case support in case MCPE now supports higher worlds but this plugin is not yet updated.

maximum world height: 127

**Comment by SOF3** [comment] 2016-07-27 08:34
@bbka123 your config file comes from WorldEditArt Beta. This issue tracker is about WorldEditArt Delta. Beta is already obsolete.

**Comment by SOF3** [comment] 2017-07-28 18:06
Implemented in libgeom.

**Closed as completed by SOF3** 2017-07-28 18:06 UTC
Labels: enhancement
